### ISSUE TITLE
Problem with long session: No enum constant org.eclipse.rdf4j.http.protocol.Protocol.Action.PING

### ISSUE THREAD

**Issue by jgrzebyta** [eclipse/rdf4j-tools#35]
```
Error while handling requestjava.lang.IllegalArgumentException: No enum constant org.eclipse.rdf4j.http.protocol.Protocol.Action.PING

at java.lang.Enum.valueOf(Enum.java:238)
at org.eclipse.rdf4j.http.protocol.Protocol$Action.valueOf(Protocol.java:25)
at org.eclipse.rdf4j.http.server.repository.transaction.TransactionController.handleRequestInternal(TransactionController.java:124)
at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:147)
at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at com.github.ziplet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:300)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:748) 
```

**Comment by jamesrdf** [comment]
Can you explain more about what happens (beyond a stack trace)? This happens when the client is running a newer version than the version, but the error message should be harmless.

**Comment by jamesrdf** [comment]
Please re-open if this is causes unexpected behaviour (beyond a stack trace) or it happens when using 2.3.0 on the server.

**Comment by jgrzebyta** [comment]
It is inside my clojure project. But roughly it is relevant to Java:

```
HTTPRepository repo = new HTTPRepository(.......) ;; to really remote rdf4j-server 
parser = Rio.createParser(...)
parser.setRDFHandler(ext RDFInserter() handleStatement(s){ super(s); ... } )
repo.init()
cnx = repo.getConnection()
cnx.begin()
parser.setParserConfig(....)
parser.parse(new FileReader(file), file.toUri().toString())
cnx.commit()
```

**Comment by jgrzebyta** [comment]
@jamesrdf I found server and client version not match. That's the reason.

**Comment by jamesrdf** [comment]
Where did you find the stacktrace? Was it in the server logs, client logs, or thrown by the client code (interrupting the execution)?
